### PR TITLE
[RCCL] Add gfx1151 support and fix some build issues

### LINKED ISSUE #2788: [Feature]: Enable RCCL on Strix Halo gfx1151
**[Migrated from original issue] ROCm/rccl#2118**

*Original issue author: @Geramy*

### Suggestion Description

Hello I have been working with lemonade-server pushing some small changes and fixes. I would like to implement a rccl plugin for thunderbolt 5 / usb4 v2, I have done some initial driver and plugin setup and I need to do a lot of other stuff but I would like to run some tests. on a gfx1151. Can you get rccl enabled for the gfx1151 for being able to use rccl to distribute load for applications such as llamacpp and lemonade-server

https://github.com/Geramy/OdinLink-Five

### Operating System

Ubuntu

### GPU

GFX1151

### ROCm Component

rccl

### PR DESCRIPTION
**Pull request by sstamenk**
## Motivation

Add RCCL support for the gfx1151 GPU target. This PR introduces gfx1151 to the supported GPU list, adds the necessary architecture guards, and fixes several build issues encountered when compiling for this target.

This PR resolves #2788 

## Technical Details

This is based on https://github.com/kyuz0/rocm-systems/pull/1 and https://github.com/ROCm/rccl/pull/2075

**1. gfx1151 architecture support:**
- Added `gfx1151` to the default GPU target list in `CMakeLists.txt`
- Added `__gfx1151__` guards alongside existing gfx11xx defines in `common.h`, `rccl_float8.h`, and `JitterBench/Common.hpp` for HW register reads and FP8 type handling
- Added `gfx1151` (and missing `gfx1101`) to the tuning index map in `tuning.cc`, mapped to index 0 (generic tuning)

**2. GENERATE_SYM_KERNELS build fix:**
- Wrapped `ncclSymkMask()` body with `#ifdef GENERATE_SYM_KERNELS`, returning 0 when symmetric kernel generation is disabled (the default). Without this guard, the function references symbols produced by `generate.py` that don't exist when the option is OFF, causing link failures.
- Fix symbol name typo in `enqueue.cc`: `ncclSymKernelCount`/`ncclSymKernelList`
  should be `ncclSymkKernelCount`/`ncclSymkKernelList` to match declarations
  in `sym_kernels.h` and definitions in `generate.py`
- Guard `kernelMask_STMC `and `kernelMask_LDMC` with `GENERATE_SYM_KERNELS`
  to silence unused variable warnings when sym kernels are disabled 

**3. CMake build fixes:**
- Fixed `ROCM_SMI_INCLUDE_DIR` typo in `target_include_directories` — this variable was never set; the correct variable is `SMI_INCLUDE_DIR`
- Added `ENABLE_COMPRESS` CMake option (default ON) to control `--offload-compress`, with automatic disable for ROCm < 6.2.0. Allows disabling compression for faster development builds via `-DENABLE_COMPRESS=OFF`.

**4. enqueue unsupported-arch logging fix:**
- Fixed `ncclPrepareTasks()` to use `agg` (not stale `task`) when logging unsupported-architecture errors in `src/enqueue.cc`.
- Prevents potential crash/segfault in that warning path and now cleanly returns `ncclInvalidUsage`.
## JIRA ID

AICOMRCCL-421

## Test Plan

- Built RCCL from the rocm-systems mono-repo targeting `gfx1151`
- Built and ran the RCCL unit test suite on a single gfx1151 GPU
- Verified RCCL loads successfully in PyTorch

## Test Result

- RCCL builds and links cleanly for gfx1151
- RCCL unit tests pass without errors - [gfx1151_rccl_unit_tests.log](https://gist.githubusercontent.com/sstamenk/5fc3bd54130acb79a0ce0b2200dec379/raw/277ece959b696470c7988d4124ad50c3dafadee3/gfx1151_rccl_unit_tests.log)
- PyTorch loads RCCL successfully and reports it as available

### Limitations

- Testing was performed on a single gfx1151 GPU only. Multi-GPU and multi-node cluster validation is still pending.

## Submission Checklist

- [x] Look over the contributing guidelines at https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.

### CODE REVIEW

**Comment by sstamenk** [comment]
Hi @eble-amd, I noticed that you were in review process for one of the earlier gfx1151 enablement PRs https://github.com/ROCm/rccl/pull/2075 that got closed during migration to rocm-systems so I thought your input here would be valuable.

File: projects/rccl/src/include/rccl_float8.h [hunk 1]
```diff
@@ -41,7 +41,7 @@ typedef struct
 } rccl_bfloat8;
 
 // __cplusplus < 201103L || (!defined(__HIP_PLATFORM_AMD__) && !defined(__HIPCC__))
-#elif HIP_VERSION >= 60300000 && !(defined(__gfx1100__) || defined(__gfx1101__) || defined(__gfx1102__) || defined(__gfx1030__))
+#elif HIP_VERSION >= 60300000 && !(defined(__gfx1030__) || defined(__gfx1100__) || defined(__gfx1101__) || defined(__gfx1102__) || defined(__gfx1151__))
```
Comment (eble-amd) [inline projects/rccl/src/include/rccl_float8.h:44]: [This comment is copied from [an earlier PR](https://github.com/ROCm/rccl/pull/2075#discussion_r2695196745).]

I'm not new to C++, but I'm new in the ROC domain, so just ignore this comment if there's no major cause for concern.

Looking at the history of this line, this used to check just HIP_VERSION because hip_fp8.h was not available before that.  Later, specific targets were added here for "[i]mproving build time."  It looks like hip_fp8.h is available in these cases, but alternative definitions are used anyway.

I am wondering about the maintainability of choosing not to include hip_fp8.h when it is available.  Is the content in the `#else` below always going to be a good substitute for what's in hip_fp8.h?  What if these definitions substantively diverge?  What if someone then includes hip_fp8.h elsewhere and uses some things that have diverged?

To focus on this PR specifically [@sstamenk]: You might want to try leaving gfx1151 out of this condition, allowing it to use the available hip_fp8.h.  I think that would avoid such maintainability concerns for this new target.  It's not my place to demand or even to steer, however.

File: projects/rccl/src/device/common.h [hunk 2]
```diff
@@ -26,7 +26,7 @@
   { __atomic_store_n((DST), (SRC), __ATOMIC_SEQ_CST); }
 #endif
 
-#if defined(__gfx1100__) || defined(__gfx1101__) || defined(__gfx1102__) || defined(__gfx1200__) || defined(__gfx1201__)
+#if defined(__gfx1100__) || defined(__gfx1101__) || defined(__gfx1102__) || defined(__gfx1151__) || defined(__gfx1200__) || defined(__gfx1201__)
```
Comment (eble-amd) [inline projects/rccl/src/device/common.h:29]: [These comments are copied from [an earlier PR](https://github.com/ROCm/rccl/pull/2075#discussion_r2698841710).]

---

I'm skeptical of this exclusion.  I sicced Codex on my TheRock workspace.  It concluded,

> I didn’t find any commits mentioning lack of s_getreg_b32/hwreg support on GFX11/12; the
    exclusions look like conservative bring‑up guards that were copied forward when new
    architectures were added. Given the AMD LLVM sources show s_getreg_b32 present for all GFX11
    (including gfx1150/1/2/3) and GFX12, there’s no historical evidence here that the instruction
    is unsupported—just that it was disabled preemptively during initial target enablement.

If this were my PR, I'd run my tests without listing gfx1151 here (and in the similar macro in tools/JitterBench/Common.hpp) and see what happens.  If the tests pass, I wouldn't mention gfx1151.

It would be helpful for a human with direct experience to comment on this condition.  Maybe it's time to trim or even to remove this list.

---

I privately contacted a developer who worked in this area four years ago.  To his memory, this condition was added because the register access wouldn't even compile for the listed targets at the time.

In conclusion, my friendly advice:
* to [@sstamenk]: don't add gfx1151 to this list unless you have evidence of a problem on gfx1151
* to RCCL code owners: maybe this exclusion has outlived its usefulness for the listed targets

File: projects/rccl/src/include/rccl_float8.h (hunk 1 above)
Comment (corey-derochie-amd) [reply projects/rccl/src/include/rccl_float8.h:44]: imo the arch gating should be within hip_fp8.h, and the `HIP_VERSION` gating should be just for support across HIP versions where the header didn't exist. I believe the architectures were added as a workaround when the arch gating was not done properly or completely within hip_fp8.h and is now being carried forward. Can this be entirely refactored now?

**Review by corey-derochie-amd — APPROVED** [review]

File: projects/rccl/src/device/common.h (hunk 2 above)
Comment (PJAvinash) [reply projects/rccl/src/device/common.h:29]: Without this exclusion we are seeing errors during linking.

**Review by speriaswamy-amd — APPROVED** [review]
Confirmed the following for gfx1151 on a single node:

- `RCCL version : 2.28.3-gfx1151-rccl:a188cf2` builds successfully.
- Unit tests complete successfully.
- rccl-tests from PR #3537 compiles and run through all tests with expected results
- RCCL initialization is correctly observed when running UTs or rccl-tests with `NCCL_DEBUG=INFO`
- sweep across all collectives and data types look good
```
NCCL_DEBUG=VERSION LD_LIBRARY_PATH=/home/stxh-4602/SP-workspace-3/rocm-systems/projects/rccl/build/release/:/opt/rocm/core/lib ./build/all_reduce_perf -b 1k -e 4g -f 2 -g 1 -n30 -w20 -M1 2>&1 | tee all_reduce_perf.log
# rccl-tests version 2.17.9-users/speriaswamy-amd/gfx1151-rccl-tests-enablement:f220897c9b rccl-headers=22803 rccl-library=22803
# Collective test starting: all_reduce_perf
# nThread 1 nGpus 1 minBytes 1024 maxBytes 4294967296 step: 2(factor) warmup iters: 20 iters: 30 agg iters: 1 validation: 1 graph: 0
#
# Using devices
#  Rank  0 Group  0 Pid 135241 on stxh-4602-MAPLE device  0 [0000:c4:00] Radeon 8050S Graphics
RCCL version : 2.28.3-gfx1151-rccl:a188cf2
HIP version  : 7.12.60430-713bdeef5b
ROCm version : 7.12.0.2-9999-713bdeef5b
Hostname     : stxh-4602-MAPLE
Librccl path : /home/stxh-4602/SP-workspace-3/rocm-systems/projects/rccl/build/release/librccl.so.1
#
#                                                              out-of-place                       in-place
#       size         count      type   redop    root     time   algbw   busbw  #wrong     time   algbw   busbw  #wrong
#        (B)    (elements)                               (us)  (GB/s)  (GB/s)             (us)  (GB/s)  (GB/s)
        1024           256     float     sum      -1     8.89    0.12    0.00       0     0.06   18.58    0.00       0
        2048           512     float     sum      -1     3.31    0.62    0.00       0     0.05   38.57    0.00       0
        4096          1024     float     sum      -1     3.59    1.14    0.00       0     0.05   81.22    0.00       0
        8192          2048     float     sum      -1     3.54    2.32    0.00       0     0.05  155.25    0.00       0
       16384          4096     float     sum      -1     3.53    4.65    0.00       0     0.05  327.03    0.00       0
       32768          8192     float     sum      -1     3.57    9.19    0.00       0     0.05  658.43    0.00       0
       65536         16384     float     sum      -1     3.65   17.97    0.00       0     0.05  1204.0    0.00       0
      131072         32768     float     sum      -1     3.90   33.58    0.00       0     0.05  2616.2    0.00       0
      262144         65536     float     sum      -1     5.01   52.29    0.00       0     0.05  4875.6    0.00       0
      524288        131072     float     sum      -1     7.27   72.13    0.00       0     0.05   10396    0.00       0
     1048576        262144     float     sum      -1    11.07   94.70    0.00       0     0.05   19624    0.00       0
     2097152        524288     float     sum      -1    26.00   80.67    0.00       0     0.05   42140    0.00       0
     4194304       1048576     float     sum      -1    48.33   86.79    0.00       0     0.05   78989    0.00       0
     8388608       2097152     float     sum      -1    94.26   89.00    0.00       0     0.05  167437    0.00       0
    16777216       4194304     float     sum      -1   184.61   90.88    0.00       0     0.05  334875    0.00       0
    33554432       8388608     float     sum      -1   321.07  104.51    0.00       0     0.05  665323    0.00       0
    67108864      16777216     float     sum      -1   614.94  109.13    0.00       0     0.05   1e+06    0.00       0
   134217728      33554432     float     sum      -1  1245.84  107.73    0.00       0     0.05   3e+06    0.00       0
   268435456      67108864     float     sum      -1  2532.10  106.01    0.00       0     0.05   5e+06    0.00       0
   536870912     134217728     float     sum      -1  5161.51  104.01    0.00       0     0.05   1e+07    0.00       0
  1073741824     268435456     float     sum      -1  10460.9  102.64    0.00       0     0.05   2e+07    0.00       0
  2147483648     536870912     float     sum      -1  21091.8  101.82    0.00       0     0.06   4e+07    0.00       0
  4294967296    1073741824     float     sum      -1  42218.5  101.73    0.00       0     0.06   7e+07    0.00       0
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 0
#
# Collective test concluded: all_reduce_perf
# GPU memory usage     : Initialization 359 MB | User-Allocated 12.0 GB | Collective 1.15 MB | Total  12.4 GB
#
```

Attached more info and logs on the ticket - AICOMRCCL-421

**Comment by sstamenk** [comment]
Points raised by @eble-amd will be addressed in a follow up PR
