### PR TITLE
[AMD-SMI] Switch to stdint.h for GO binding support

### LINKED ISSUE #5195: [Issue]:  GO API Bindings broken since v7.1.0
The commit 924a06d1e16cae0ecee07f519ff2bbe254bb9f72 introduces an issue such that `goamdsmi.go` no longer compiles, because a C include has been switched to a C++ include, which Golang does not natively support.

```suggestion
- #include <stdint.h>
+ #include <cstdint>
```

For example, the [AMD SMI Prometheus Exporter](https://github.com/amd/amd_smi_exporter/blob/master/src/Makefile), encounters this issue when running `make` for all release versions 7.1 and higher. While it is no longer in development, it is the canonical example project for building against the GO API bindings, and is linked in the [GO API Documentation](https://rocm.docs.amd.com/projects/amdsmi/en/latest/how-to/amdsmi-go-lib.html#add-amd-smi-library-to-your-project).

```
go get github.com/ROCm/amdsmi@amd-staging
go: downloading github.com/ROCm/amdsmi v0.0.0-20251117222445-a044536b8d69
go: added github.com/ROCm/amdsmi v0.0.0-20251117222445-a044536b8d69
go build -o amd_smi_exporter main.go cpu_data.go
# github.com/ROCm/amdsmi
../../../go/pkg/mod/github.com/!r!o!cm/amdsmi@v0.0.0-20251117222445-a044536b8d69/goamdsmi.go:29:10: fatal error: cstdint: No such file or directory
   29 | #include <cstdint>
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:11: build] Error 1
```

<br>
I'm happy to provide a PR to fix this.

### PR DESCRIPTION
**Pull request by harkgill-amd**
## Motivation

Resolves https://github.com/ROCm/rocm-systems/issues/5195.

## Technical Details

https://github.com/ROCm/rocm-systems/commit/924a06d1e16cae0ecee07f519ff2bbe254bb9f72 broke go bindings by switching to `cstdint`. Reverting back to `stdint.h` resolve this.

## JIRA ID

N/A

## Test Plan

- Build a sample `main.go` test file with `go build`.

## Test Result

- Prior to the patch, builds fails with 
```
/home/rocm/go/pkg/mod/github.com/!r!o!cm/amdsmi@v0.0.0-20251117222445-a044536b8d69/goamdsmi.go:29:10: fatal error: cstdint: No such file or directory
   29 | #include <cstdint>
      |          ^~~~~~~~~
compilation terminated.
```
- Post patch, build is successful.

## Submission Checklist

- [ ] Look over the contributing guidelines at https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.

### CODE REVIEW

File: projects/amdsmi/goamdsmi.go [hunk 1]
```diff
@@ -26,7 +26,7 @@ package goamdsmi
 /*
 #cgo CFLAGS: -Wall -I/opt/rocm/include
 #cgo LDFLAGS: -L/opt/rocm/lib -L/opt/rocm/lib64 -lgoamdsmi_shim64 -Wl,--unresolved-symbols=ignore-in-object-files
-#include <cstdint>
+#include <stdint.h>
```
Comment (oliveiradan) [inline projects/amdsmi/goamdsmi.go:29]: Do we have any needs to use `C++` and namespaces? If so, `<cstdint>` header is the way to go. 
If that is not the case, than `<stdint.h>` would be fine.

Comment (harkgill-amd) [reply projects/amdsmi/goamdsmi.go:29]: There is no need for `<cstdint>` as far as I can tell. 

cgo section in `goamdsmi.go` is passed to to C compiler with `import "C"` - compilation will fail if you pass in `<cstdint>` as it doesn't exist in the C standard library. `amdsmi_go_shim.c` is purely a .c file. 

Neither uses C++ or namespaces.

**Review by oliveiradan — APPROVED** [review]
Questions answered. Approved!

**Review by marifamd — APPROVED** [review]
