### PR TITLE
[rocshmem] Add rocshmem_hipmodule_init API for CUDA graph compatibility

### LINKED ISSUE #2741: [Feature]: rocshmem API for compatibility with cuda.graph capture
**[Migrated from original issue] ROCm/rocSHMEM#323**

*Original issue author: @hebais*

### Problem Description

Hello, here is my situation:
1. I have a python binding that calls rocshmem init on the host side (python binding links librocshmem.a)
2. I have a triton kernel that invokes rocshmem api on device side (however it links librocshmem bc code)
So the host's ctx and triton kernel device's context are not the same, I tride to call rocshmem_get_device_ctx on host side and pass it to triton kernel, and it works. However, this does not work when inside torch.cuda.graph(). Since the hipMemcpyFromSymbol is always based on the legacy stream (which is not allowed by cuda.graph)

Is there a way to implement nvshmemx_cumodule_init like API ?

Thanks

### Operating System

Ubuntu 22.04

### CPU

AMD

### GPU

MI300x

### ROCm Version

6.3

### ROCm Component

_No response_

### Steps to Reproduce

_No response_

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by drprajap**
This commit adds a new API rocshmem_hipmodule_init() that allows
user-compiled HIP modules or device bitcode modules to be initialized with
rocSHMEM device contexts. This is essential for CUDA graph compatibility.

This API replaces manual rocshmem ctx management via rocshmem_get_device_ctx()
during JIT compilation.

Resolves: https://github.com/ROCm/rocm-systems/issues/2741

## JIRA ID
 Resolves AIROCSHMEM-145

## Test Plan

Functional test is added to verify module loading after successfully setting device global symbol.

## Submission Checklist

- [ ] Look over the contributing guidelines at https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.

### CODE REVIEW

File: projects/rocshmem/src/rocshmem_gpu.cpp [hunk 1]
```diff
@@ -114,17 +114,78 @@ __device__ void rocshmem_wg_finalize() {}
...
+  if (err != hipSuccess) {
+    fprintf(stderr, "[rocSHMEM] Error: Failed to get ROCSHMEM_CTX_DEFAULT symbol from module: %s\n",
+            hipGetErrorString(err));
+    return -1;
+  }
+
+  if (symbol_size != sizeof(rocshmem_ctx_t)) {
+    fprintf(stderr, "[rocSHMEM] Error: Symbol size mismatch. Expected %zu, got %zu\n",
+            sizeof(rocshmem_ctx_t), symbol_size);
+    return -1;
```
Comment (Yiltan) [inline projects/rocshmem/src/rocshmem_gpu.cpp]:
```suggestion
    return ROCSHMEM_ERROR;
```

File: projects/rocshmem/src/rocshmem_gpu.cpp [hunk 2]
```diff
@@ -114,17 +114,78 @@ __device__ void rocshmem_wg_finalize() {}
...
+
+  if (err != hipSuccess) {
+    fprintf(stderr, "[rocSHMEM] Error: Failed to get address of built-in ROCSHMEM_CTX_DEFAULT: %s\n",
+            hipGetErrorString(err));
+    return -1;
+  }
+
+  if (source_ctx_device == nullptr) {
+    fprintf(stderr, "[rocSHMEM] Error: Built-in ROCSHMEM_CTX_DEFAULT has null address\n");
+    return -1;
```
Comment (Yiltan) [inline projects/rocshmem/src/rocshmem_gpu.cpp]:
```suggestion
    return ROCSHMEM_ERROR;
```

File: projects/rocshmem/src/rocshmem_gpu.cpp [hunk 3]
```diff
@@ -114,17 +114,78 @@ __device__ void rocshmem_wg_finalize() {}
...
-                             sizeof(rocshmem_ctx_t)));
+                                sizeof(rocshmem_ctx_t)));
   return ctx.ctx_opaque;
+}
+
+__host__ int rocshmem_hipmodule_init(hipModule_t module, hipStream_t stream) {
+  // Step 1: Get device address of rocSHMEM's built-in ROCSHMEM_CTX_DEFAULT symbol
+  // Use hipGetSymbolAddress for graph-capture compatibility (device-to-device path)
+  void *source_ctx_device = nullptr;
+  hipError_t err = hipGetSymbolAddress(&source_ctx_device, HIP_SYMBOL(ROCSHMEM_CTX_DEFAULT));
```
Comment (Yiltan) [inline projects/rocshmem/src/rocshmem_gpu.cpp:132]: Is there a reason we're not using `CHECK_HIP(...)` in this function?

File: projects/rocshmem/src/rocshmem_gpu.cpp [hunk 4]
```diff
@@ -114,17 +114,78 @@ __device__ void rocshmem_wg_finalize() {}
...
+
+  err = hipMemcpyAsync(
+      target_ctx_device,
+      source_ctx_device,
+      sizeof(rocshmem_ctx_t),
+      hipMemcpyDeviceToDevice,  // Device-to-device copy for graph capture compatibility
+      stream
+  );
+
+  if (err != hipSuccess) {
```
Comment (abouteiller) [inline projects/rocshmem/src/rocshmem_gpu.cpp:182]: CHECK_HIP again

File: projects/rocshmem/tests/functional_tests/hipmodule_init_tester.cpp [hunk 5]
```diff
@@ -0,0 +1,262 @@
...
+                                        int loop, size_t size) {
+  // Note: This test intentionally ignores gridSize/blockSize parameters and uses
+  // a simple 1x1x1 launch.
+  (void)gridSize;
+  (void)blockSize;
+  (void)loop;
+  (void)size;
+
+  if (my_pe == 0) {
+    printf("\n=== CUDA/HIP graph capture test ===\n");
```
Comment (abouteiller) [inline projects/rocshmem/tests/functional_tests/hipmodule_init_tester.cpp]:
```suggestion
    printf("\n=== HIP graph capture test ===\n");
```

**Review by abouteiller — APPROVED** [review]

File: projects/rocshmem/src/rocshmem_gpu.cpp (hunk 3 above)
Comment (drprajap) [reply projects/rocshmem/src/rocshmem_gpu.cpp:132]: CHECK_HIP macro aborts and exits the program instead of returning gracefully, For this API, I think failing from the API and let user decide what they want to do with failure is better approach hence I have not used CHECK_HIP macro

File: projects/rocshmem/tests/functional_tests/tester.hpp [hunk 6]
```diff
@@ -126,6 +126,7 @@ enum TestType {
   FloodGetTestType = 86,
   FloodGetNBITestType = 87,
   FloodGTestType = 88,
+  HipModuleInitTestType = 89,
```
Comment (abouteiller) [inline projects/rocshmem/tests/functional_tests/tester.hpp:129]: Should we run that test case in CI?

**Review by abouteiller — APPROVED** [review]

File: projects/rocshmem/tests/functional_tests/tester.hpp (hunk 6 above)
Comment (drprajap) [reply projects/rocshmem/tests/functional_tests/tester.hpp:129]: yes. Is there any other place that need a change to run this in CI?

File: projects/rocshmem/scripts/functional_tests/driver.sh
Comment (abouteiller) [inline projects/rocshmem/scripts/functional_tests/driver.sh:476]:
```suggestion
ExecTest  "hipmodule_init    2       1            1

```

Comment (abouteiller) [inline projects/rocshmem/scripts/functional_tests/driver.sh:671]:
```suggestion
ExecTest  "hipmodule_init    2       1            1

```

File: projects/rocshmem/scripts/functional_tests/driver.sh [hunk 7]
```diff
@@ -665,6 +667,7 @@ TestGDA() {
   #       | Name             | Ranks | Workgroups | Threads | Max Message Size #
   ##############################################################################
   ExecTest  "init"             2       1            1
+ExecTest  "hipmodule_init    2       1            1
```
Comment (abouteiller) [inline projects/rocshmem/scripts/functional_tests/driver.sh]:
```suggestion
  ExecTest  "hipmodule_init"   2       1            1
```

File: projects/rocshmem/scripts/functional_tests/driver.sh [hunk 8]
```diff
@@ -471,6 +472,7 @@ TestOther() {
...
```
Comment (abouteiller) [inline projects/rocshmem/scripts/functional_tests/driver.sh]:
```suggestion
  ExecTest  "hipmodule_init"   2       1            1
```

**Comment by abouteiller** [comment]
Looks like the hiprtc is missing a dependency to compile the dynamic code in the CI @drprajap

**Comment by drprajap** [comment]
> Looks like the hiprtc is missing a dependency to compile the dynamic code in the CI @drprajap

yes, because local testing has rocm path set in environment, this was not exposed in my testing, I have explicitly included it now

File: projects/rocshmem/src/rocshmem_gpu.cpp [hunk 9]
```diff
@@ -114,17 +114,78 @@ __device__ void rocshmem_wg_finalize() {}
 
 
 /******************************************************************************
-* These host APIs use Device side symbol - ROCSHMEM_CTX_DEFAULT so it needs
+* These host API use Device side symbol - ROCSHMEM_CTX_DEFAULT so it needs
```
Comment (omor1) [inline projects/rocshmem/src/rocshmem_gpu.cpp:117]:
```suggestion
* This host API use Device side symbol - ROCSHMEM_CTX_DEFAULT so it needs
```

**Comment by omor1** [comment]
I think I'm somewhat confused as to why the compiled hiprtc kernel defines its own `ROCSHMEM_CTX_DEFAULT` symbol instead of using the one from the compiled library that it should link to. I'm not especially familiar with the hiprtc APIs and how to use them though, so I'm likely simply not understanding something about the workflow.

**Comment by drprajap** [comment]
> I think I'm somewhat confused as to why the compiled hiprtc kernel defines its own `ROCSHMEM_CTX_DEFAULT` symbol instead of using the one from the compiled library that it should link to. I'm not especially familiar with the hiprtc APIs and how to use them though, so I'm likely simply not understanding something about the workflow.

Current test is not using existing rocshmem device library kernels for hiprtc compilation because that requires pulling up lots of dependencies for kernel compilation, I tried that and with existing rocshmem device API definitions, it is not minimal effort. So I chose to orchestrate `ROCSHMEM_CTX_DEFAULT` device side symbol definition in a minimal device kernel module compilation. The goal of this minimal unit level functional test is to verify Device module initialization path for given compiled module using existing host allocated 'ROCSHMEM_CTX_DEFAULT' symbol and see if new rocshmem_hipmodule_init API is able to get and set the device side symbols without any API compatibility issue.
