### PR TITLE
Make AQLProfile v2 headers C compatible

### LINKED ISSUE #5576: [aqlprofile] aqlprofile-sdk/aql_profile_v2.h not compatible with C compilation
# aqlprofile v2 SDK Header Is Not C-Compatible

## Summary

The ROCm-installed `aqlprofile-sdk/aql_profile_v2.h` header is exposed as a C
SDK header and wraps declarations in `extern "C"` for C++ consumers, but it does
not currently compile as C. The header contains C++-only type usage and C++
member initializers in public declarations.

This prevents C translation units from including the v2 aqlprofile SDK header
directly. In HRX integration, the workaround was to compile the C source
that includes this header as C++.

## Header Location

Observed header:

```text
/srv/vm-shared/projects/pyre-workspace/rocm/include/aqlprofile-sdk/aql_profile_v2.h
```

This is made visible by the ROCm `hsa-runtime64` CMake package via:

```text
/srv/vm-shared/projects/pyre-workspace/rocm/lib/cmake/hsa-runtime64/hsa-runtime64Targets.cmake
```

where `hsa-runtime64::hsa-runtime64` publishes:

```cmake
INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
```

## Reproducer

```bash
cat >/tmp/aql.c <<'EOF'
#include "aqlprofile-sdk/aql_profile_v2.h"
int main(void) { return 0; }
EOF

clang -x c -std=c11 \
  -I/srv/vm-shared/projects/pyre-workspace/rocm/include \
  -fsyntax-only /tmp/aql.c
```

## Diagnostics

```text
aql_profile_v2.h:503:50: error: must use 'struct' tag to refer to type 'aqlprofile_att_buffer_status_t'
aql_profile_v2.h:619:48: error: expected ';' at end of declaration list
aql_profile_v2.h:620:56: error: expected ';' at end of declaration list
aql_profile_v2.h:621:56: error: expected ';' at end of declaration list
aql_profile_v2.h:759:29: error: must use 'enum' tag to refer to type 'aqlprofile_spm_decode_query_t'
```

### `aqlprofile_att_buffer_status_t` Is Not Typedef'd

The header declares a tagged struct:

```c
struct aqlprofile_att_buffer_status_t {
  uint64_t _size;
  void* data;
  uint64_t read_size;
  uint64_t num_swaps;
  bool needs_swap;
  bool is_too_late;
  bool error;
};
```

but later uses the tag name as a typedef name:

```c
hsa_status_t aqlprofile_att_update_buffer_status(
    aqlprofile_att_buffer_status_t* out,
    aqlprofile_handle_t handle,
    int shader_engine_id,
    int flags);
```

That is valid C++, but not valid C. In C, either the use must be
`struct aqlprofile_att_buffer_status_t*`, or the struct must be typedef'd.

Suggested C-compatible form:

```c
typedef struct aqlprofile_att_buffer_status_t {
  uint64_t _size;
  void* data;
  uint64_t read_size;
  uint64_t num_swaps;
  bool needs_swap;
  bool is_too_late;
  bool error;
} aqlprofile_att_buffer_status_t;
```

### Struct Members Use C++ Default Initializers

The header declares:

```c
typedef struct aqlprofile_spm_available_configuration_t {
  aqlprofile_spm_parameter_type_t type = AQLPROFILE_SPM_PARAMETER_TYPE_NONE;
  uint64_t min_interval = 0;
  uint64_t max_interval = 0;
} aqlprofile_spm_available_configuration_t;
```

Default member initializers are C++, not C.

Suggested C-compatible form:

```c
typedef struct aqlprofile_spm_available_configuration_t {
  aqlprofile_spm_parameter_type_t type;
  uint64_t min_interval;
  uint64_t max_interval;
} aqlprofile_spm_available_configuration_t;
```

### `aqlprofile_spm_decode_query_t` Is Not Typedef'd

The header declares:

```c
enum aqlprofile_spm_decode_query_t {
  AQLPROFILE_SPM_DECODE_QUERY_SEG_SIZE = 0,
  AQLPROFILE_SPM_DECODE_QUERY_NUM_XCC,
  AQLPROFILE_SPM_DECODE_QUERY_EVENT_COUNT,
  AQLPROFILE_SPM_DECODE_QUERY_COUNTER_MAP_BYTE_OFFSET,
  AQLPROFILE_SPM_DECODE_QUERY_LAST
};
```

but later uses it as a typedef name:

```c
hsa_status_t aqlprofile_spm_decode_query(
    aqlprofile_spm_buffer_desc_t desc,
    aqlprofile_spm_decode_query_t query,
    uint64_t* param_out);
```

That is valid C++, but not valid C. In C, either the use must be
`enum aqlprofile_spm_decode_query_t`, or the enum must be typedef'd.

Suggested C-compatible form:

```c
typedef enum aqlprofile_spm_decode_query_t {
  AQLPROFILE_SPM_DECODE_QUERY_SEG_SIZE = 0,
  AQLPROFILE_SPM_DECODE_QUERY_NUM_XCC,
  AQLPROFILE_SPM_DECODE_QUERY_EVENT_COUNT,
  AQLPROFILE_SPM_DECODE_QUERY_COUNTER_MAP_BYTE_OFFSET,
  AQLPROFILE_SPM_DECODE_QUERY_LAST
} aqlprofile_spm_decode_query_t;
```

## Expected Result

The public SDK header should compile as C when included from a C translation
unit:

```bash
clang -x c -std=c11 -I<rocm-prefix>/include -fsyntax-only /tmp/aql.c
```

It should also continue to compile from C++ translation units. In my C based system, I'm using a manually forked/fixed version of the header and it would be good to fix upstream.

### PR DESCRIPTION
**Pull request by ammarwa**
## Summary
- Make `aqlprofile-sdk/aql_profile_v2.h` C-compatible by typedefing the tagged ATT buffer status struct and SPM decode query enum.
- Apply the same typedef fixes to the ROCProfiler-SDK internal AQLProfile copy.
- Add shipped CTest coverage for both standalone AQLProfile and ROCProfiler-SDK so C translation units include and use the previously broken declarations.

Fixes #5576

## Testing
- `cmake -S projects/aqlprofile -B /tmp/rocm-systems-5576-aqlprofile-build -DAQLPROFILE_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release`
- `cmake --build /tmp/rocm-systems-5576-aqlprofile-build --target aql-profile-v2-test aql-profile-v2-c-compatibility-test -j 8`
- `ctest --test-dir /tmp/rocm-systems-5576-aqlprofile-build -R "^(AqlProfileV2Test\.|aql-profile-v2-c-compatibility-test$)" --output-on-failure`
- `cmake -S projects/rocprofiler-sdk -B /tmp/rocm-systems-5576-rocprofiler-sdk-build-fresh -DROCPROFILER_BUILD_TESTS=ON -DROCPROFILER_BUILD_AQLPROFILE=ON -DCMAKE_BUILD_TYPE=Release`
- `cmake --build /tmp/rocm-systems-5576-rocprofiler-sdk-build-fresh --target aqlprofile-core-tests -j 8`
- `ctest --test-dir /tmp/rocm-systems-5576-rocprofiler-sdk-build-fresh -R "^unit\.aqlprofile\.core\." --output-on-failure`
- `/opt/rocm/lib/llvm/bin/clang -x c -std=c11 -I/tmp/rocm-systems-5576-aqlprofile-build/src/core/include -Iprojects/aqlprofile/src/core/include -I/opt/rocm/include -fsyntax-only projects/aqlprofile/src/core/tests/aql_profile_v2_c_test.c`
- `/opt/rocm/lib/llvm/bin/clang -x c -std=c11 -I/tmp/rocm-systems-5576-rocprofiler-sdk-build-fresh/source -Iprojects/rocprofiler-sdk/source -I/opt/rocm/include -fsyntax-only projects/rocprofiler-sdk/source/lib/aqlprofile/core/tests/aql_profile_v2_c_test.c`
- `cmake --install /tmp/rocm-systems-5576-rocprofiler-sdk-build-fresh --prefix /tmp/rocm-systems-5576-rocprofiler-sdk-install --component tests` reached and installed `aqlprofile-core-tests`, its generated unit-test cmake, and `aql_profile_v2_c_test.c`; it later stopped on unrelated unbuilt `aqlprofile-pm4-tests`.
- `custom-ai-secret-scan --repo-root /home/aelwazir/work/.worktrees/rocm-systems-aqlprofile-c-compatible-headers`

## Review
- Ran comprehensive reviewer roles across implementation, tests, naming/domain, clean code, AMD alignment, design/API, and final narrow review.
- Addressed reviewer findings by staging both C test sources, aligning the SDK test with the `unit.aqlprofile.core.*` path, preserving C++ default member initializer behavior under `__cplusplus`, and folding the SDK C translation-unit check into `rocprofiler_add_unit_test` so installed tests include it.

### CODE REVIEW

File: projects/rocprofiler-sdk/source/lib/aqlprofile/aql_profile_v2.h [hunk 1]
```diff
@@ -673,9 +673,15 @@ typedef enum
 
 typedef struct aqlprofile_spm_available_configuration_t
 {
+#if defined(__cplusplus)
     aqlprofile_spm_parameter_type_t type         = AQLPROFILE_SPM_PARAMETER_TYPE_NONE;
     uint64_t                        min_interval = 0;
     uint64_t                        max_interval = 0;
```
Comment (MythreyaK) [inline projects/rocprofiler-sdk/source/lib/aqlprofile/aql_profile_v2.h]: I will be opening a PR very soon that will sync aqlprofile changes (including this revert #5352 that removes these lines) that were added after the migration snapshot. So, these commit ranges 588c5210bc0229f11e6abbccd883bd090f380cc4...7f2a32efdf43491a64ffc867fe8523600cc2f796 (image because this diff range can't be scoped to a folder).

<details><summary>aqlprofile diff</summary>Image </details>

https://github.com/ROCm/rocm-systems/commits/develop/projects/aqlprofile

**Review by ApoKalipse-V — APPROVED** [review]
+1 for the PR, but need to address Mythreya's comment

File: projects/rocprofiler-sdk/source/lib/aqlprofile/aql_profile_v2.h (hunk 1 above)
Comment (MythreyaK) [reply projects/rocprofiler-sdk/source/lib/aqlprofile/aql_profile_v2.h]: We can merge this PR before or after, 

* If we merge this _before_ my PR, then I think it will probably be easier to review my upcoming PR if we skip the rocprofiler-sdk's aqlprofile changes. I will sync these changes in my PR. 
* If we merge this _after_ my PR, then the changes you are making will be identical to both headers, making your PR simpler. 

I am okay with either.

Comment (ammarwa) [reply projects/rocprofiler-sdk/source/lib/aqlprofile/aql_profile_v2.h]: Sure but let us address this ASAP, send me your changes to review and then we can push these changes to add the test to make sure we don't see this problem later

Comment (MythreyaK) [reply projects/rocprofiler-sdk/source/lib/aqlprofile/aql_profile_v2.h]: ~~Opened~~ Merged #5588, so we can go with approach 2.

**Comment by MythreyaK** [comment]
PR #5588 was merged. This will need a rebase. 

Thanks for the help!

**Review by MythreyaK — APPROVED** [review]

**Review by itrowbri — APPROVED** [review]
